// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN5bDIPcBLZWceUCN41QrdqKAYI0cx7lw',
    appId: '1:249735466547:web:a98237f4c57fdb3e1c5d46',
    messagingSenderId: '249735466547',
    projectId: 'easybudgetai-c7f44',
    authDomain: 'easybudgetai-c7f44.firebaseapp.com',
    databaseURL: 'https://easybudgetai-c7f44-default-rtdb.firebaseio.com',
    storageBucket: 'easybudgetai-c7f44.firebasestorage.app',
    measurementId: 'G-7H7EZ77RR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgt9hflSJZUh__6Mgm0sULLSJAQjIIrNA',
    appId: '1:249735466547:android:7cf75aafef0ec5ac1c5d46',
    messagingSenderId: '249735466547',
    projectId: 'easybudgetai-c7f44',
    databaseURL: 'https://easybudgetai-c7f44-default-rtdb.firebaseio.com',
    storageBucket: 'easybudgetai-c7f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3e_zeBRYiNS6XKCIg5YqoJ7HLzH_Ja8',
    appId: '1:249735466547:ios:f60592c6c93056f21c5d46',
    messagingSenderId: '249735466547',
    projectId: 'easybudgetai-c7f44',
    databaseURL: 'https://easybudgetai-c7f44-default-rtdb.firebaseio.com',
    storageBucket: 'easybudgetai-c7f44.firebasestorage.app',
    iosClientId: '249735466547-geta6p3nvaqn83jl79jggu4p2uvtiue7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easybudgetai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr3e_zeBRYiNS6XKCIg5YqoJ7HLzH_Ja8',
    appId: '1:249735466547:ios:f60592c6c93056f21c5d46',
    messagingSenderId: '249735466547',
    projectId: 'easybudgetai-c7f44',
    databaseURL: 'https://easybudgetai-c7f44-default-rtdb.firebaseio.com',
    storageBucket: 'easybudgetai-c7f44.firebasestorage.app',
    iosClientId: '249735466547-geta6p3nvaqn83jl79jggu4p2uvtiue7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easybudgetai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN5bDIPcBLZWceUCN41QrdqKAYI0cx7lw',
    appId: '1:249735466547:web:3cd6fa72058744031c5d46',
    messagingSenderId: '249735466547',
    projectId: 'easybudgetai-c7f44',
    authDomain: 'easybudgetai-c7f44.firebaseapp.com',
    databaseURL: 'https://easybudgetai-c7f44-default-rtdb.firebaseio.com',
    storageBucket: 'easybudgetai-c7f44.firebasestorage.app',
    measurementId: 'G-68TQBG8CY7',
  );
}
